apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: free5gc
spec:
  destination:
    name: ''
    namespace: free5gc
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s/30.free5gc/helm
    repoURL: 'https://gitlab.com/atosnet/cluster-5g.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../values.yaml
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

