apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aop-cluster
  namespace: argo
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: operator/app
    repoURL: https://gitlab.com/atosnet/crd.git
    targetRevision: main
  syncPolicy: {}
