apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
spec:
  destination:
    name: ''
    namespace: elastic
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s/elk-bitnami/elasticsearch-kibana-stack/helm
    repoURL: 'https://gitlab.com/atosnet/cluster.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../values-modified.yaml
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions: []