apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pushgateway
spec:
  destination:
    name: ''
    namespace: pushgateway
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s/pushgateway/helm
    repoURL: 'https://gitlab.com/atosnet/cluster.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../values.yaml
  project: default
  syncPolicy:
    syncOptions:
      - PrunePropagationPolicy=foreground
    automated:
      prune: false
      selfHeal: false