apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-cluster
spec:
  destination:
    name: ''
    namespace: victoriametrics
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s/victoria-metrics/victoria-metrics-cluster/helm
    repoURL: 'https://gitlab.com/atosnet/cluster.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../values.yaml
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
